#!/usr/bin/env bash

# copy configs to .config
# sudo rsync -aP --exclude=setup . ~/.config

# Add the i3 repo with gaps
/usr/lib/apt/apt-helper download-file https://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2023.02.18_all.deb keyring.deb SHA256:a511ac5f10cd811f8a4ca44d665f2fa1add7a9f09bef238cdfad8461f5239cc4

sudo apt install ./keyring.deb

echo "deb http://debian.sur5r.net/i3/ $(grep '^DISTRIB_CODENAME=' /etc/lsb-release | cut -f2 -d=) universe" | sudo tee /etc/apt/sources.list.d/sur5r-i3.list

# install dependencies and softwares
sudo apt update && sudo apt install -y i3 clipit kitty zsh neofetch rofi ripgrep feh polybar picom flameshot autoconf gcc make pkg-config libpam0g-dev libcairo2-dev libfontconfig1-dev libxcb-composite0-dev libev-dev libx11-xcb-dev libxcb-xkb-dev libxcb-xinerama0-dev libxcb-randr0-dev libxcb-image0-dev libxcb-util0-dev libxcb-xrm-dev libxkbcommon-dev libxkbcommon-x11-dev libjpeg-dev


rm ./keyring.deb

# download and decompress nvim 
wget https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz -O ~/nvim-linux64.tar.gz && sudo tar -zxvf ~/nvim-linux64.tar.gz -C ~/

# remove nvim tar
rm ~/nvim-linux64.tar.gz

# install oh my zsh
sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# make home font dir
mkdir ~/.fonts

# install zscroll
git clone https://github.com/noctuid/zscroll ~/.config
sudo python3 ~/.config/zscroll/setup.py install
rm -rf ~/.config/zscroll/

# install playercltd to get spotify data
wget https://github.com/altdesktop/playerctl/releases/download/v2.4.1/playerctl-2.4.1_amd64.deb -O ~/.config/playerctl.deb
sudo dpkg -i ~/.config/playerctl.deb
rm ~/.config/playerctl.deb

# change neofetch theme
git clone https://github.com/Chick2D/neofetch-themes/ ~/.config
cat ~/.config/neofetch-themes/small/dotfetch.conf > ~/.config/neofetch/config.conf
rm -rf ~/.config/neofetch-themes/


# download meslo fonts
wget https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf -P ~/.fonts

# install i3lock-color for betterlockscreen
git clone https://github.com/Raymo111/i3lock-color.git ~/.config
./~/.config/i3lock-color/install-i3lock-color.sh
rm -rf ~/.config/i3lock-color


# change to zsh
sudo chsh -s $(which zsh)

# check if nvim in path, if not add it
if grep -Fxq "path+=('$(echo ~)/nvim-linux64/bin')" ~/.zshrc
then 
  echo NVIM PATH ALREADY IN ~/.zshrc , SKIPPING!
else
  echo "path+=('$(echo ~)/nvim-linux64/bin')" >> ~/.zshrc
fi

# add p10k theme to omz
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

# check if theme is p10k, if not replace default omz theme with p10k
if grep -Fxq 'ZSH_THEME="powerlevel10k/powerlevel10k"' ~/.zshrc
then
  echo P10K ALREADY DEFAULT THEME IN ~/.zshrc , SKIPPING! 
else
  sed -i -e 's|ZSH_THEME=.*$|ZSH_THEME="powerlevel10k/powerlevel10k"|' ~/.zshrc
fi

# add local bin to path
if grep -Fxq "path+=('$(echo ~)/.local/bin')" ~/.zshrc
then 
  echo NVIM PATH ALREADY IN ~/.zshrc , SKIPPING!
else
  echo "path+=('$(echo ~)/.local/bin')" >> ~/.zshrc
fi

echo \n END OF SCRIPT, YOU NEED TO SOURCE THE ~/.zshrc FROM ZSH SHELL
